name: Deploy code from git to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Create directory if it doesn't exist
          mkdir -p /home/ec2-user/data
          
          # Create a temporary directory for the deployment
          TEMP_DIR=$(mktemp -d)
          cd $TEMP_DIR
          
          # Clone the repository using configurable URL
          git clone ${{ secrets.REPOSITORY_URL }} .
          
          # Sync the contents to the destination directory (excluding .git)
          rsync -av --delete --exclude='.git' --exclude='.github' ./ /home/ec2-user/data/
          
          # Cleanup
          cd /
          rm -rf $TEMP_DIR
