name: Deploy code from git to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.EC2_SSH_KEY }}
        known_hosts: unnecessary
        if_key_exists: replace

    - name: Adding Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy with rsync
      run: |
        # Create the deploy script
        echo "#!/bin/bash
        mkdir -p /home/ec2-user/data
        cd /home/ec2-user/data
        git clone ${{ secrets.REPOSITORY_URL }} .
        " > deploy.sh
        
        # Make the script executable
        chmod +x deploy.sh
        
        # Copy the script and execute it
        scp deploy.sh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:~/deploy.sh
        ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} './deploy.sh'
